SELECT C.APNT_NO, C.PT_NAME, C.PT_NO, D.MCDP_CD, D.DR_NAME, C.APNT_YMD
FROM (SELECT A.PT_NO, PT_NAME, APNT_NO, APNT_YMD, MDDR_ID
      FROM PATIENT A JOIN APPOINTMENT B 
      ON A.PT_NO = B.PT_NO
      WHERE APNT_YMD LIKE "2022-04-13%" AND APNT_CNCL_YN = 'N' AND MCDP_CD = 'CS') C 
      JOIN DOCTOR D ON C.MDDR_ID = D.DR_ID
ORDER BY C.APNT_YMD